### ISSUE TITLE
Implementation of cashier functionality support

### ISSUE THREAD

**Issue by sg777** [chips-blockchain/pangea-poker#235]
Cashier has to provide three basic functionalities.
1. show balance
Showing the balance info of the CHIPS and LN wallets in the back end.
The json sent from GUI to backend for this is
```
{
method : "get_bal_info"
}
```
In return from backend to GUI the below info is pushed
```
{
method: "bal_info"
chips_bal: some_amount in CHIPS
ln_bal: some_amount in CHIPS
}
```
2. deposit 
Showing the add_info info of the CHIPS and LN wallets in the back end, to which player will deposit the funds at the end of the game.

The json sent from GUI to backend for this is
```
{
method : "get_addr_info"
}
```
In return from backend to GUI the below info is pushed
```
{
method: "addr_info"
chips_addr: some_amount in CHIPS
ln_addr: some_amount in CHIPS
}
```
3. witdraw
It is to withdraw funds from CHIPS and LN wallets
The json sent from GUI to backend for this is
```
{
method : "withdraw"
addr: CHIPS address
amount: amount_to_be_withdrawn
from_wallet: 0 or 1 (0 means from CHIPS wallet, 1 means from LN wallet)
}
```
In return from backend to GUI the below info is pushed
```
{
method: "withdraw_info"
tx_id: withdrawl_tx
}
```

**Comment by sg777** [comment]
I see it's already displaying chips amount, so if we click on withdraw and if it send balance and addr json to the backend I think we are done with this.

**Comment by sg777** [comment]
Based on the existing GUI, I'll change functionalities into two parts.
For deposit
GUI sends backend
```
{
method: "wallet_info"
}
in response backend sends the GUI the following info
```
{
method: "wallet_info"
chips_addr: chips_wallet_addr
chips_bal: some_amount
ln_addr: ln_wallet_addr
ln_bal: some_amount
}
```
2. For withdraw, same as mentioned above.
```

**Comment by piggydoughnut** [comment]
@sg777 The actual message about the wallet I am receiving right now is 
```
 { method: "walletInfo", addr: "bCrYjDLNgY4Vo5roWTsEshLhPd6Rsk8Jg3", balance: 0.340755 }
```

I receive that as one of the first things when I join the table with a custom IP. So I assume that stays unchanged, but you will just add the `ln_addr` and `ln_bal` there?

**Comment by sg777** [comment]
Below is the relation between the request and response messages between the GUI and BE.
`withdrawRequest(GUI request) -->withdrawResponse(BE response) `
The `withdrawResponse` message contains the following fields:
1. balance --> Available balance to withdraw
2. tx_fee--> The tx_fee that you have to pay to withdraw
3. addrs--> Can only withdraw the CHIPS to any one of these addresses listed here.

`withdraw(GUI Request) --> withdrawInfo(BE response)`
The BE is expecting addr and amount in the `withdraw` request from the GUI, in response the BE is sending tx_details of the amount withdrawn in the `withdrawInfo` response.

**Comment by piggydoughnut** [comment]
@sg777 how would you send error messages? What do I receive if something went wrong with the transaction?
