### ISSUE TITLE
Add some time after the hand finishes to show the winner

### ISSUE THREAD

**Issue by NutellaLicka** [chips-blockchain/pangea-poker#25]
Instead of going into the next hand straight away, is there a way to add a couple of seconds after the hand finishes, for people to digest who won the hand and with what cards.

~Also, if a log of each bet could be added in a text box down the bottom left corner of the display. So people can see a text log of each hand/bet played on the table.~

**Comment by norbertdragan** [comment]
Made #29 for your second suggestion.

**Comment by norbertdragan** [comment]
I believe there is sufficient time now, and I also created #80 so that the hand history will contain board cards and player cards.
