### ISSUE TITLE
Ask the person whether they are a player or a dealer on start

### ISSUE THREAD

**Issue by NutellaLicka** [chips-blockchain/pangea-poker#27]
Instead of having all 3 options (dealer/player1/player2) selectable at the start, maybe just prompt "Are you a Dealer or a Player?", then go into the next menu to add the appropriate IP data. For players, instead of selecting player 1 or 2, have the nodes connect and then select a seat, which then defines what player number they are.

https://i.gyazo.com/4003a0e86e261409a23df751dd4ec406.png

**Comment by norbertdragan** [comment]
I agree that this modal doesn't have the best UX but we will get rid of it later as it is only needed during the test period.
