### ISSUE TITLE
Player funds are negative

### ISSUE THREAD

**Issue by norbertdragan** [chips-blockchain/pangea-poker#30]
On the test nodes, one of the player's balance is `-1`. This should not be possible.

I thought that once a player's fund reaches zero, it will automatically recharge to 200. Also, the some of the two player's funds should always be `400`. Am I wrong about it?

<img width="221" alt="image" src="https://user-images.githubusercontent.com/17296915/67618576-c288f000-f7e0-11e9-9331-a7195cf68c04.png">
<img width="349" alt="image" src="https://user-images.githubusercontent.com/17296915/67618618-34f9d000-f7e1-11e9-901f-6675bc61073f.png">

**Comment by sg777** [comment]
Agreed, in any case the player funds shouldn't be -ve. I'll check, if you find this repeating in a specific scenario please share the details of it.

Yes, sum of the players funds is always 400, until any player does the refill. Say for example if player1 went all-out and lost and in the next hand he refill 200 more, in that case sum of funds on the table equates to 600.

**Comment by norbertdragan** [comment]
This has been solved by @sg777 refilling the player funds.
