### ISSUE TITLE
can you create dockerfile for front end

### ISSUE THREAD

**Issue by imylomylo** [chips-blockchain/pangea-poker#339]
hi @piggydoughnut can you dockerize this repo plz, be handy for testing.  no rush, but sometime in october would be good :+1:

**Comment by piggydoughnut** [comment]
Will do this week! 🖖🏽 @imylomylo

**Comment by piggydoughnut** [comment]
done :) https://hub.docker.com/repository/docker/piggydoughnut/pangea-poker 🖖🏽
