### ISSUE TITLE
Incorrect minRaiseTo calculation

### ISSUE THREAD

**Issue by norbertdragan** [chips-blockchain/pangea-poker#36]
<a href="http://i.norbert.dev/3240bb" target="_blank"><img src="https://d2rsw2kbemic8w.cloudfront.net/items/0j1T171h0L1h0j351X2B/Image%202019-10-30%20at%204.38.37%20PM.png" style="display: block;height: auto;width: 100%;"/></a>

### Actions on the flop
1. Player1 opens with a bet of `2`
2. Player 2's turn

### Expected behavior
The Raise button should show `Raise to 4`, due to`minRaiseTo` being `4`.

### Actual behavior
The Raise button shows`Raise to 6`, due to`minRaiseTo` being `6`.

### Thoughts
Not sure why this is happening. Player1's first action to open with a bet of `2` is being interpreted by the backend as a raise (`possibilities: [4]`) -- however, technically it is called a _bet_, because there are no prior bets in this betting round that the player can raise compared to.

I don't think we need to create a new backend message type for the `possibilities`, raise should be fine, but the GUI should receive the proper number.

**Comment by norbertdragan** [comment]
Turns out this issue is also prevalent in all streets, not just post-flop. See below

**Comment by norbertdragan** [comment]
<a href="http://i.norbert.dev/19e0df" target="_blank"><img src="https://d2rsw2kbemic8w.cloudfront.net/items/0Y1N2N2V0a3q0k3H3b1V/Image%202019-10-31%20at%204.59.35%20PM.png" style="display: block;height: auto;width: 100%;"/></a>

### Actions pre-flop
- Player1 raises to `4`

## Expected behavior
The Raise button should show `Raise to 6`, due to `minRaiseTo` being `6`.

`minRaiseTo` should be calculated as follows: 

Current `toCall` + (current `toCall` - `previous toCall`)

So:  `4 + (4 -2) = 6`

`minRaiseTo` should be `6`.

**Comment by norbertdragan** [comment]
Same thing here.

<a href="http://i.norbert.dev/964dd1" target="_blank"><img src="https://d2rsw2kbemic8w.cloudfront.net/items/0K313623021d3c322S2n/Image%202019-10-31%20at%205.00.47%20PM.png" style="display: block;height: auto;width: 100%;"/></a>


### Actions pre-flop
- Player1 raises to `10`

### Expected behavior
The Raise button should show `Raise to 18`, due to `minRaiseTo` being `18`.

`minRaiseTo` should be calculated as follows: 

Current `toCall` + (current `toCall` - previous `toCall`)

So:  `10 + (10 -2) = 18`

`minRaiseTo` should be `18`.

**Comment by norbertdragan** [comment]
@sg777 the minimum raise is always the next increment of what the previous player has raised _with_ -- or in other words, the difference of the bet the previous had to call and the total amount the player raised to.

**Comment by sg777** [comment]
In the backend it was considering as `bet` as `raise`, for that reason the after the bet the next raise it's showing `bet+2*previous_raise`, I'll fix this.

**Comment by norbertdragan** [comment]
I'm reopening this issue because the calculation is still not correct.

**Pre-flop, blinds: 1/2**
1. Player1 (SB) raises to `6`
2. For Player2 (BB), the `minRaiseTo` should be `10`, **not** `14`.

But it is `14`:

<a href="http://i.norbert.dev/875188" target="_blank"><img src="https://d2rsw2kbemic8w.cloudfront.net/items/3I2Q0n0z0o2M201L3E1H/Image%202019-11-19%20at%204.19.55%20PM.png" style="display: block;height: auto;width: 100%;"/></a>

**Comment by norbertdragan** [comment]
Another scenario, post-flop. Player1's `minRaiseTo` should be `52`.

<a href="http://i.norbert.dev/e6029e" target="_blank"><img src="https://d2rsw2kbemic8w.cloudfront.net/items/0P3I3d1u3e2X062I1G1Y/Image%202019-11-19%20at%204.30.30%20PM.png" style="display: block;height: auto;width: 100%;"/></a>

**Comment by norbertdragan** [comment]
@sg777 as a reminder, `minRaiseTo` should be calculated as follows:

Current `toCall` + (current `toCall` - previous `toCall`).

**Comment by norbertdragan** [comment]
Fixed by chips-blockchain/bet@32562df.
