### ISSUE TITLE
DCV crashes with "Bus error" during the second hand

### ISSUE THREAD

**Issue by norbertdragan** [chips-blockchain/pangea-poker#40]
The first hand plays just fine. During the second hand, however, DCV crashes with `Bus error (core dumped)` every time when using the current test nodes.

**Comment by sg777** [comment]
I tested with the `tag: v0.1.1`  of `Pangea-Poker` repo, with the updated backend nodes. Can you please test and share the crash logs if this issue repeats.

**Comment by norbertdragan** [comment]
This issue is again active when using chips-blockchain/bet@32562df.

**Comment by sg777** [comment]
I synced your nodes, and tested with the latest bet changes, Can you please see if you still getting the bus error.
If possible can you make some video, where can I see list of actions or backend logs to debug if the issue still persists.

**Comment by norbertdragan** [comment]
Hey, the issue still persists. I have recorded you a video of me struggling to play for 20 minutes. Here it is: https://share.getcloudapp.com/E0uEqx8w

### Timestamps

- `00:00` to `04:30`: I struggle to get play a single hand. Player 2 seems to fail to connect.
- `04:30`: The first hand that I can play. I play it so Player 1 folds on the Flop. Crash happens at `05:29` during the beginning of the second hand without any player action.
- `05:40` to `8:00`: Can't play any hands. `Failed to send data` or `Table is filled` error messages.
- `08:00`: The second hand I can play. This time I go till Showdown. DCV crashes at `09:25` during the second hand without any player action.
- `09:30` to `17:50`: I can't play any hands. I am trying different combinations of `Start` and `Reset` but still getting the usual `Failed to send data` or `Table is filled` errors.
- `17:50`: The third hand I can play. This time I went All-In on the turn. Crash happens at `19:11` without any player action. 
- `19:30`: The fourth hand I can play. This time I went All-In pre-flop. Crash happens at `20:24` during the second hand, without any player action.
- `20:37`: The fifth hand I can play. The first action was fold. Crash happens at `21:30` without any player action during the second hand.

### Some takeaways
- During the first ~17 minutes I was only able to play 2x hands. `Failed to send data` was the most common error.
- The only way I was able to trigger the game to start is to hit `Reset`. I was unable to start the game using `Start`. I got `Table is filled` error every time I tried to connect via `Start`. I still don't understand how this works.
- The game crashes every time we advance to the next hand regardless of what actions were taken during the first hand.
- There is no need for players to perform any actions. The game crashes even there is no action.

Let me know if there is something I can do differently. @sg777 I would also appreciate a video from you using the test backend nodes with playing multiple consecutive hand being played.

**Comment by sg777** [comment]
I can see the reason for most of these crashes is the way it's playing. The order in which the backend nodes get started results in the `Failed to send data`.
Ideally at the moment the sequence of actions that are accepting is.
1. All the backend nodes started in the following order, dcv, bvv and followed by any playing node.
2. In the GUI front nodes can connect to backend nodes in any order, but once the connection is established for the first hand dealer should press `start`, even `reset` also fine but will check that part.
Will investigate and share more details soon.

**Comment by norbertdragan** [comment]
Thanks for the clarification! Now it seems like the game plays without any crashes at all.

To sum up, the order af actions that need to be done:

1. Start `dcv` node
2. Start `bvv` node
3. Start `palyer` nodes
4. Connect to the nodes on the GUIs
5. Click `Start` on the dealer GUI
6. Click `SIT HERE` on each of the player nodes
7. PLAY!

I will add this to the documentation soon.

 I am closing this issue as this seem to be solved.
