### ISSUE TITLE
Handle player sitting out

### ISSUE THREAD

**Issue by piggydoughnut** [chips-blockchain/pangea-poker#429]
- [x] style controls 
- [x] show controls when its not players active turn
- [x] send `sitout` to the backend at the end of the game if the player continues or not

**Comment by sg777** [comment]
The backend expecting the sitout info from the GUI is as follows:
Where the value 0 means the player is not opting for sitout or the player is willing to play next hand.
```
{
method: sitout
 value : 0
}
```
