### ISSUE TITLE
Sitout enhancement

### ISSUE THREAD

**Issue by sg777** [chips-blockchain/pangea-poker#445]
- [x] Retaining the value of sitout checkbox.
- [x] Providing the ability for the players to send the sitout info anytime to the backend. Since this is needed in the scenario where when the player likes to sitback.
- [ ] At the beginning of each hand, check if the current player is sitting out, if yes -> show sitting out badge

**Comment by piggydoughnut** [comment]
Cannot do the last task since the current implementation of the sitout does not allow the player to be at the table.
