### ISSUE TITLE
No way to know who is the currently active player

### ISSUE THREAD

**Issue by norbertdragan** [chips-blockchain/pangea-poker#47]
The backend should send a message to all the players informing the UI which player is currently active. The message should be sent at the same time the `round_betting` method is being sent to the currently active player.

This will be very important to have for 2+ player tables. Also, it's currently blocking #17 and #20.

**Comment by sg777** [comment]
From the backend, earlier round_betting method has been pushed only to the player which is currently active. In this commit https://github.com/chips-blockchain/bet/commit/d9c8ca4b3a2f39784da2f20a478b8f806c255f29 changes are made such that the turn info i.e round_betting method is received by all the players. 

However changes has to done in the GUI by @norbertdragan to prevent the betting controls of non active players.
