### ISSUE TITLE
Hole cards get exposed during the River, before the Show Down

### ISSUE THREAD

**Issue by norbertdragan** [chips-blockchain/pangea-poker#48]
If one player folds during the River (the last `boardCard`), the backend sends `allHoleCardsInfo` for both of the players. This should not happen, hole cards should only be disclosed if all of the River bets _get called_, which is called the Show Down.

See this video from 00:54: https://i.norbert.dev/a534bf

The bet on the River does not get called, the `allHoleCardsInfo` array gets filled up with the all players' cards. This should not be the behavior.

**Comment by sg777** [comment]
In this commit https://github.com/chips-blockchain/bet/commit/f5b65b4f91b4860ac8f90db251c2f41e76d2f8e8 changes are made not to expose the cards in showndown during the fold scenario.

**Comment by norbertdragan** [comment]
Thanks for fixing it!
