### ISSUE TITLE
All-in does not progress when one player has chips

### ISSUE THREAD

**Issue by norbertdragan** [chips-blockchain/pangea-poker#50]
<a href="http://i.norbert.dev/dbb203" target="_blank"><img src="https://d2rsw2kbemic8w.cloudfront.net/items/2U0P0l2V1F252d1H2N3h/Image%202019-11-25%20at%206.35.01%20PM.png" style="display: block;height: auto;width: 100%;"/></a>

In the above scenario, `player1` went All-In before the flop and `player2` called. Since there is only one player left with funds (as it is currently `player_funds: [0, 200]`), it is impossible to do any more betting, therefore the showdown has to begin Pre-Flop. 

`finalInfo` has to be sent to the players before the flop. It is the equivalent of both players going All-In with equal stacks (eg. if it was `player_funds: [0, 0]`).

If there was a third player who had chips (eg. `player_funds: [0, 200, 200]`), _then_ the betting round has to continue and we will have to create a side pot that the `player1` cannot win. But that's only once we get pass heads-up.

**Comment by sg777** [comment]
It has been fixed here https://github.com/chips-blockchain/bet/commit/5651c443b23f09c5667b3c5e84ca7da52f0031a9.

**Comment by norbertdragan** [comment]
Unfortuntaly, I cannot test wether it is fixed due to #40.

**Comment by norbertdragan** [comment]
I just tested it again and `finalInfo` is not arriving once one palyer is All-In and the other called with a bigger stack.

Screenshot: 
![image](https://user-images.githubusercontent.com/17296915/70892203-fadeca80-1fe8-11ea-84a6-2e8edaa694a9.png)

**Comment by norbertdragan** [comment]
Seems like it's fixed by 6a4c8d7. Thank you @sg777!
