### ISSUE TITLE
Re-raise should not be possible when the one opponent is All-In

### ISSUE THREAD

**Issue by norbertdragan** [chips-blockchain/pangea-poker#51]
<a href="http://i.norbert.dev/2e825f" target="_blank"><img src="https://d2rsw2kbemic8w.cloudfront.net/items/0q0G213H2q1e0i1k3q0b/Image%202019-11-25%20at%206.33.42%20PM.png" style="display: block;height: auto;width: 100%;"/></a>

In the above scenario, re-raise should not be possible, only the Call and Fold buttons should be displayed.

**Comment by norbertdragan** [comment]
This has been partially addressed in #55 - going forward `possibilities` will be interpreted by the front-end.  However, to fix this issue, the backend still needs to be modified by @sg777.

**Comment by sg777** [comment]
In the back end the changes are made, such that if all other players in the game left with no funds like in the above mentioned scenario, reraise should not happen and the changes to reflect that has been made here https://github.com/chips-blockchain/bet/commit/5651c443b23f09c5667b3c5e84ca7da52f0031a9

**Comment by norbertdragan** [comment]
Thanks!

The front-end is now processes the controls from the backend, so it's fixed by #55/
