### ISSUE TITLE
Stack is negative for BB at the start of a new hand

### ISSUE THREAD

**Issue by norbertdragan** [chips-blockchain/pangea-poker#59]
![image](https://user-images.githubusercontent.com/17296915/70312967-f8c08300-1814-11ea-940f-eb6fa570f07e.png)

When a new hand starts after an All-In, the palyer at the Big Blind has negative stack. The problem appears to be that the first `round_betting` message does not have `player_funds` property, as seen bleow.

![image](https://user-images.githubusercontent.com/17296915/70313775-86e93900-1816-11ea-9d07-2331e3e2bd62.png)

**Comment by sg777** [comment]
This issue has been fixed in the commit https://github.com/chips-blockchain/bet/commit/6bde00e87bab8260d2305dd5e118b969d16c6fc2 in which I made changes to push the player_funds in round_betting method.
