### ISSUE TITLE
Call button is not responsive during All-In

### ISSUE THREAD

**Issue by norbertdragan** [chips-blockchain/pangea-poker#61]
In some cenarios, when one player goes All-In, the other cannot call it, because the button is not responding. Furhter investiagtion is needed.

**Comment by norbertdragan** [comment]
Sentry erorr log: https://sentry.io/share/issue/688c2c09ae43460b8cdff6ee0e6b309d/

**Comment by sg777** [comment]
This arises only in scenarios, say suppose if the player with higher funds goes all-in.

Let's say player1 has 202 chips and player2 has 198 chips. 

If Player2 goes all-in then the call-198 button is responsive for the player1 and no issues in this scenario.

If Player1 goes all-in then the call-198 button is not responsive for the player2.
