### ISSUE TITLE
Backend is not responding for All-In when `possibilities: [6]` is sent

### ISSUE THREAD

**Issue by norbertdragan** [chips-blockchain/pangea-poker#63]
Currently, the front-end is sending `possibilities: [4]` even if the player goes All-In. When I fixed this and properly sent `[6]` to the backend, the game stopped responding.

Scenario:
1. SB Calls raises to 4
2. BB Re-raises to 200 and is All-In
3. Backend is frozen.

I am wondering how important it is to actually send `possibilities: [6]`. Does that make any difference in the game? All-in can happen by calling or by raising or even by posting the blinds. 

Therefore maybe we should just ignore this possibility and remain using `raise` instead?

![image](https://user-images.githubusercontent.com/17296915/70442157-06387000-1a96-11ea-8361-4b28c14e87e8.png)

![image](https://user-images.githubusercontent.com/17296915/70442082-d9845880-1a95-11ea-8388-3eb58a2794f3.png)

**Comment by sg777** [comment]
The issue has been fixed with the recent commits, can you please check if the issue still exists.
