### ISSUE TITLE
Split pot is not handled by the front-end

### ISSUE THREAD

**Issue by norbertdragan** [chips-blockchain/pangea-poker#79]
There is no mechanism to split the pot when two or more players have the same hand. The backend does handle it, but at this point it's unclear what the message is.

@sg777 can you please clarify how `finalInfo` is different when the pot is split? Is it simply the `winners` array having multiple elements, eg `winners: [0, 1]`?

### TODOs
- [x] Update the logic to be able to do a basic split
- [x] Update animations
- [x] Update logs
- [x] Add tests

**Comment by sg777** [comment]
In the `finalInfo` I'll add the winning amounts or the specific field when there is a pot split. At the moment in the backend, the corresponding invoices are getting paid to the players during the pot split and that specific information is not pushed onto the GUI yet.

**Comment by norbertdragan** [comment]
@sg777 can we keep the current data structure and simply append the subsequent winners to the `winners` array and keep `win_amount` the amount each player wins?

For example, if the total pot is 800, and is split for two people: 
```
method: "finalInfo",
[..]
win_amount: 400,
winners: [0, 1]
```
