### ISSUE TITLE
Design Cashier feature

### ISSUE THREAD

**Issue by norbertdragan** [chips-blockchain/pangea-poker#82]
The [cashier protocol](https://github.com/chips-blockchain/bet/blob/master/cashier_protocol.md) has been implemented by @sg777. The frontend needs to catch up, however, there are still some clarifications that are needed.

See the [Design Proposal](https://github.com/chips-blockchain/pangea-poker/issues/82#issuecomment-581763826).

**Comment by norbertdragan** [comment]
A few questions @sg777:

1. What happens if the player doesn't have enough funds?
2. How to know to which address the player needs to deposit the funds to? (step 3.2 in the cashier protocol [documentation](https://github.com/chips-blockchain/bet/blob/master/cashier_protocol.md)
3. How can a player withdraw these funds later?

**Comment by sg777** [comment]
1. If the players don't have enough funds, in the backend I'm displaying the message `can't afford to fund this transaction` but this needs to be pushed on to the GUI to let the users know about it.
2. Players can deposit funds to any new address or the existing address that belongs to the wallet of running backend chips node. As we go by, we can provide some efficient mechanism such that when the player connects to the backend, we can display some address on to the GUI along with the funds the player has.
3. If the player wins the funds will automatically gets deposited to the players backend wallet, and to withdraw these funds from the backend wallet, player has to withdraw by creating a tx using chips-cli, to ease this process if you can provide some option in the GUI where the user can enter the chips address to which he wants to withdraw and just by clicking withdraw he can withdraw the amount to any desired address.[Though here we need to add some security check to prevent false withdrawls and I'll think of it later]

**Comment by norbertdragan** [comment]
Cool, thanks for clarification. I have edited the first comment with some new TODOs on how we can move forward.

**Comment by norbertdragan** [comment]
I have created a couple diagrams to demonstrate my suggestion for the user flow and the flow of funds. I am looking for feedback on how this could be improved, whether it is technically feasible (@sg777) and if I have missed something (or any other feedback).

### The Flow of the Funds
![funds-flow](https://user-images.githubusercontent.com/17296915/73718587-d6fc5300-4714-11ea-9a02-1bba4a07019f.jpg)

- There are 3 places where the funds can live: 
  - Outside the application, e.g. in an external wallet.
  - In the main Pangea Poker wallet - this is used to fund the tables the player is connected to.
  - At the table where the player is currently playing.
- From an external wallet, the players can deposit funds to the Pangea Poker wallet.
- From the Pangea Poker wallet, the players can withdraw funds to any other address.
- From the Pangea Poker wallet, the players can move funds to the table to use as their stack.
- From the table, the players can move the funds back to the Pangea Poker wallet (only by leaving the table).

### Deposit/Withdrawal User Flow

![user-flow-funds-deposit-withdraw](https://user-images.githubusercontent.com/17296915/73719703-2001d680-4718-11ea-975f-f3c929b9e757.jpg)

*Click to enlarge diagram*

The above diagram shows my recommendation for the user flow. Please let me know if any of the steps need further clarification.

**Comment by norbertdragan** [comment]
### Screens
They are showing a 9-max table, since the UI designs were originally designed to target that. The same principles will apply to the heads-up game as well. 

#### 1. Seat selection, after the player joined the table
Adds balance display, a button to get to the cashier, and a prompt to the player on what to do.

![01-join-table](https://user-images.githubusercontent.com/17296915/73720413-c9959780-4719-11ea-8042-25e708135330.jpg)
<img width="800" alt="image" src="https://user-images.githubusercontent.com/17296915/73720393-bedb0280-4719-11ea-9628-38f87b2cfc44.png">

#### 2. Set buy-in
The Buy-In component re-uses the pattern of the Controls component to reduce additional work. We also display to the other players that a new player is in the process of joining the table. 

![02-set-buy-in](https://user-images.githubusercontent.com/17296915/73720565-314be280-471a-11ea-80a5-5964aa4be19f.jpg)
<img width="800" alt="image" src="https://user-images.githubusercontent.com/17296915/73720799-b931ec80-471a-11ea-9927-e54ff64eb87f.png">

#### 3. Balance is too low
In case the balance is too low, we prompt the user to deposit. When they click on the Deposit Funds button, the cashier opens up with the Deposit tab active.

![03-balance-is-too-low](https://user-images.githubusercontent.com/17296915/73720937-07df8680-471b-11ea-9c2e-27c166b76680.jpg)
<img width="800" alt="image" src="https://user-images.githubusercontent.com/17296915/73721098-59881100-471b-11ea-88dd-4d51fc8fb5f5.png">

#### 4. Cashier - Deposit
The player can see the available balance, the address to deposit to, and some additional information to help them top up. We might also display the minimum and maximum buy-in for the table.

The player can also click on the address to copy it to the clipboard. We can think about implementing a QR code feature in future iterations.

![04-deposit](https://user-images.githubusercontent.com/17296915/73721369-f6e34500-471b-11ea-8773-b39018754472.jpg)
<img width="800" alt="image" src="https://user-images.githubusercontent.com/17296915/73721488-47f33900-471c-11ea-8fa5-54da5acd2756.png">

#### 5. Cashier - Withdraw
The player can withdraw funds to any specified address. A Max button helps to set the input field to all of the available Pangea wallet balance (which does not include any funds currently at the table).

@sg777 mentioned that developing this feature has some security implications that we need to work out, therefore it probably will be implemented at a later stage.

We will also need to think about states here, and possibly a second layer of confirmation ("Are you sure to withdraw X to Y?") to avoid accidental wrong withdrawals.

![05-withdraw](https://user-images.githubusercontent.com/17296915/73721692-bafcaf80-471c-11ea-85df-6cbef3c17a16.jpg)
<img width="800" alt="image" src="https://user-images.githubusercontent.com/17296915/73721832-fb5c2d80-471c-11ea-98b9-f6a5b6acda38.png">

#### 6. Leave table
The player needs to have a method of leaving the table without closing the browser window. This feature and the screens are TBD (To Be Designed). 

Please let me know what feedback you have regarding these screens. Is everything clear? What am I missing?

**Comment by imylomylo** [comment]
Remove “Deposit Funds” button.  Seems redundant if the “Cashier” button were moved to the bottom permanently & it then remains in the line-of-sight of the user when setting buy in, because they may not have enough for calling or raising.

**Comment by norbertdragan** [comment]
@imylomylo you mean if the "Cashier" button were moved to the _top right_ permanently? Yes, you might be right that displaying both buttons might be a bit redundant, but I think it also makes it easier for the player to take the right action, and it doesn't have any other negative implications I can think of.

**Comment by imylomylo** [comment]
Bottom right.

**Comment by norbertdragan** [comment]
We already have the Controls component at the bottom right (see screenshot below), therefore, keeping the Cashier button there all the time is not feasible. 

Also, it's a totally legit scenario that a player wants to access the Cashier _before_ they run out of chips, so we need to have it displayed somewhere in the UI at all times. But I wouldn't put it to the same level as the Controls, as it the Cashier is only needed rather infrequently. 

![Flop - Bet](https://user-images.githubusercontent.com/17296915/73815075-c9120500-47dc-11ea-9495-05b6ca474ea9.jpg)

**Comment by imylomylo** [comment]
OK cool.  Yeah all times definitely.  I thought maybe it could have been displayed at bottom right at all times, but seems not.

Thanks for taking time to consider :+1:

**Comment by norbertdragan** [comment]
Closing as the design has been completed.
