### ISSUE TITLE
Use `initialState.ts` to test for state instead of `testState.ts`

### ISSUE THREAD

**Issue by norbertdragan** [chips-blockchain/pangea-poker#95]
Having two separate sources for testing is sub-optimal, as tests can miss miss errors if `initialState` gets modified, plus having to maintain two files causes extra work.

**Comment by piggydoughnut** [comment]
It s better to keep the `testState` for tests since now it will be hard to test for certain things using `initialState` because the game is becoming more dynamic.

e.g. There is no predefined user seating setup, which tests need as an input. The user seating will be coming from the backend.
